### ISSUE TITLE
Cometa

### ISSUE THREAD

**Issue by mixlaab** [mixlaab/miPrimerRepo#5]
Quiero agregar **cometas**
![cometa](https://user-images.githubusercontent.com/47201674/59969898-217ee580-951f-11e9-8a5a-f62ac30977c1.jpg)

**Comment by 134360** [comment]
Los cometas caen del espacio a gran velocidad  chocando contra atmósfera y mostrándonos las lluvias de estrellas

**Comment by katherinegr** [comment]
ya quedo solucionado lo del cometa .....
