### ISSUE TITLE
Dragones

### ISSUE THREAD

**Issue by mixlaab** [mixlaab/miPrimerRepo#7]
Quiero añadir dragones salvajes a mi poema

**Comment by MarioZuniga13** [comment]
Necesito agregar algo sobre Dragones al poema.

![](http://tuscriaturas.blogia.com/upload/20060809175052-dragon-de-dussia.jpg)

**Comment by MarioZuniga13** [comment]
Voy a agregar el siguiente párrafo:

**Cazador impetuoso que se lanza al combate
contra los caballeros de brillante armadura,
con rugido estruendoso que al suelo los abate.​**
